version: '3'
services:
  db:
    image: postgres
    container_name: bryin_db
    restart: always
    user: "${UID}:${GID}"
    env_file:
      - .env-db
    volumes:
      - .:/var/lib/postgresql/data
    expose:
      - 5432
  redis:
    container_name: bryin_redis
    image: redis
    depends_on:
      - db
    restart: always
  webapp:
    container_name: bryin_webapp
    depends_on:
      - db
    restart: always
    volumes:
      - .static:/static
      - .media:/media
    env_file:
      - .env-bryin
    build: src/
    expose:
      - 8000
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - .static:/static
      - .media:/media
    ports:
      - "127.0.0.1:42230:80"
    depends_on:
      - webapp
